# Utiliser l'image officielle de MySQL 8.0 comme base
FROM mysql:8.0

# (Optionnel) Copier des scripts d'initialisation personnalisés
# COPY ./init.sql /docker-entrypoint-initdb.d/

# (Optionnel) Copier un fichier de configuration personnalisé
# COPY ./my.cnf /etc/mysql/conf.d/my.cnf

# Exposer le port par défaut de MySQL
EXPOSE 3306
