name: Simple Test Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Test simple backend
  backend-simple-test:
    name: Backend Simple Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo

    - name: Check PHP version
      run: php --version

    - name: Check if composer.json exists
      working-directory: ./gestion-hospitaliere-backend
      run: |
        if [ -f "composer.json" ]; then
          echo "✅ composer.json found"
          cat composer.json
        else
          echo "❌ composer.json not found"
          exit 1
        fi

    - name: Install Dependencies (without dev)
      working-directory: ./gestion-hospitaliere-backend
      run: |
        composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader || {
          echo "❌ Composer install failed"
          exit 1
        }

    - name: Check Laravel installation
      working-directory: ./gestion-hospitaliere-backend
      run: |
        if [ -f "artisan" ]; then
          echo "✅ Laravel artisan found"
          php artisan --version
        else
          echo "❌ Laravel artisan not found"
          exit 1
        fi

  # Test simple frontend
  frontend-simple-test:
    name: Frontend Simple Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Check Node version
      run: |
        node --version
        npm --version

    - name: Check if package.json exists
      working-directory: ./gestion-hospitaliere-frontend
      run: |
        if [ -f "package.json" ]; then
          echo "✅ package.json found"
          cat package.json
        else
          echo "❌ package.json not found"
          exit 1
        fi

    - name: Install Dependencies
      working-directory: ./gestion-hospitaliere-frontend
      run: |
        npm ci || {
          echo "❌ npm install failed"
          npm install --legacy-peer-deps
        }

    - name: Check React installation
      working-directory: ./gestion-hospitaliere-frontend
      run: |
        if [ -d "node_modules/react" ]; then
          echo "✅ React installed"
        else
          echo "❌ React not found"
          exit 1
        fi
